# Generated by Django 2.0.5 on 2018-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interruption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('cause', models.IntegerField(choices=[(1, 'Cause')])),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('setting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('realization', models.FloatField()),
                ('planned', models.FloatField()),
                ('is_taken', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('waste', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=True, to='cms_app.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='interruption',
            name='order',
            field=models.ForeignKey(on_delete=True, to='cms_app.Order'),
        ),
    ]
