# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Interruption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Początek przestoju')),
                ('stop_date', models.DateTimeField(blank=True, null=True, verbose_name='Koniec przestoju')),
                ('cause_1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Przyczyna przestoju 1')),
                ('cause_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Przyczyna przestoju 2')),
                ('cause_3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Przyczyna przestoju 3')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Czy przestój jest zamknięty?')),
                ('was_alerted', models.BooleanField(default=False, verbose_name='Czy przestój jest zamknięty?')),
            ],
            options={
                'verbose_name': 'Przestój',
                'verbose_name_plural': 'Przestoje',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Nazwa maszyny')),
                ('setting', models.IntegerField(verbose_name='Nastawa maszyny')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Czy maszyna jest w tej chwili zajęta?')),
            ],
            options={
                'verbose_name': 'Maszyna',
                'verbose_name_plural': 'Maszyny',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True, verbose_name='Numer zlecenia')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start zlecenia')),
                ('stop_date', models.DateTimeField(blank=True, null=True, verbose_name='Koniec zlecenia')),
                ('planned', models.FloatField(verbose_name='Planowane wykonanie')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Zlecenie zakończone')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.Machine', verbose_name='Maszyna')),
            ],
            options={
                'verbose_name': 'Zlecenie',
                'verbose_name_plural': 'Zlecenia',
            },
        ),
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start realizacji')),
                ('stop_date', models.DateTimeField(blank=True, null=True, verbose_name='Koniec realizacji')),
                ('realization', models.FloatField(blank=True, null=True, verbose_name='Wykonano')),
                ('waste', models.FloatField(blank=True, null=True, verbose_name='Ilość odpadów')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy realizacja jest aktywna?')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.Order', verbose_name='Zlecenie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Osoba odpowiedzialna')),
            ],
            options={
                'verbose_name': 'Realizacja',
                'verbose_name_plural': 'Realizacje',
            },
        ),
        migrations.AddField(
            model_name='interruption',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.Machine', verbose_name='Maszyna'),
        ),
        migrations.AddField(
            model_name='interruption',
            name='realization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_app.Realization', verbose_name='Realizacja'),
        ),
    ]
