# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interruption',
            options={'verbose_name': 'Przestoj', 'verbose_name_plural': 'Przestoje'},
        ),
        migrations.AlterField(
            model_name='interruption',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Czy przestoj jest zamkniety?'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='start_date',
            field=models.DateTimeField(verbose_name='Poczatek przestoju'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='was_alerted',
            field=models.BooleanField(default=False, verbose_name='Czy przestoj jest zamkniety?'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Czy maszyna jest w tej chwili zajeta?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Zlecenie zakonczone'),
        ),
        migrations.AlterField(
            model_name='realization',
            name='waste',
            field=models.FloatField(blank=True, null=True, verbose_name='Ilosc odpadow'),
        ),
    ]
