# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_auto_20181209_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=256, verbose_name='Nazwisko')),
                ('is_busy', models.BooleanField(default=False, verbose_name='Czy pracownik jest zajęty?')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRealization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Początek pracy')),
                ('stop_date', models.DateTimeField(blank=True, null=True, verbose_name='Koniec pracy')),
                ('position', models.CharField(max_length=256)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.Employee', verbose_name='Pracownik')),
                ('realization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.Realization', verbose_name='Realizacja')),
            ],
        ),
    ]
