# Generated by Django 2.0.5 on 2018-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_auto_20180904_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='realization',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waste',
            field=models.FloatField(null=True),
        ),
    ]
