# Generated by Django 2.0.5 on 2018-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_auto_20180904_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
