# Generated by Django 2.0.5 on 2018-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_machine_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Czy maszyna jest w tej chwili zajęta?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(verbose_name='Numer zlecenia'),
        ),
    ]
