# Generated by Django 2.0.5 on 2018-09-10 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_app', '0008_auto_20180910_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start zlecenia')),
                ('stop_date', models.DateTimeField(blank=True, null=True, verbose_name='Koniec zlecenia')),
                ('realization', models.FloatField(blank=True, null=True, verbose_name='Wykonano')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Zlecenie zajęte')),
                ('waste', models.FloatField(blank=True, null=True, verbose_name='Ilość odpadów')),
            ],
            options={
                'verbose_name': 'Zlecenie',
                'verbose_name_plural': 'Zlecenia',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_taken',
        ),
        migrations.RemoveField(
            model_name='order',
            name='realization',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waste',
        ),
        migrations.AddField(
            model_name='realization',
            name='order',
            field=models.ForeignKey(on_delete=True, to='cms_app.Order', verbose_name='Zlecenie'),
        ),
        migrations.AddField(
            model_name='realization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='Osoba odpowiedzialna'),
        ),
    ]
