# Generated by Django 2.0.5 on 2018-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_auto_20180910_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realization',
            name='is_taken',
        ),
        migrations.AddField(
            model_name='order',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Zlecenie zajęte'),
        ),
    ]
