# Generated by Django 2.0.5 on 2018-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0010_auto_20180910_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zlecenie', 'verbose_name_plural': 'Zlecenia'},
        ),
        migrations.AlterModelOptions(
            name='realization',
            options={'verbose_name': 'Realizacja', 'verbose_name_plural': 'Realizacje'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_taken',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(unique=True, verbose_name='Numer zlecenia'),
        ),
        migrations.AlterField(
            model_name='realization',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start realizacji'),
        ),
        migrations.AlterField(
            model_name='realization',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Koniec realizacji'),
        ),
    ]
