# Generated by Django 2.0.5 on 2018-09-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0012_auto_20180910_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interruption',
            name='cause',
            field=models.IntegerField(choices=[(1, 'Cause')], null=True, verbose_name='Przyczyna przestoju'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='stop_date',
            field=models.DateTimeField(null=True, verbose_name='Koniec przestoju'),
        ),
    ]
