# Generated by Django 2.0.5 on 2018-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0015_auto_20180911_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interruption',
            name='cause',
            field=models.IntegerField(blank=True, choices=[(1, 'Cause')], null=True, verbose_name='Przyczyna przestoju'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='stop_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Koniec przestoju'),
        ),
    ]
