# Generated by Django 2.0.5 on 2018-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0017_auto_20180911_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruption',
            name='machine',
            field=models.ForeignKey(default=None, on_delete=True, to='cms_app.Machine', verbose_name='Maszyna'),
            preserve_default=False,
        ),
    ]
