# Generated by Django 2.0.5 on 2018-09-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0018_interruption_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interruption',
            name='cause',
        ),
        migrations.AddField(
            model_name='interruption',
            name='cause_1',
            field=models.IntegerField(blank=True, choices=[(1, 'Cause')], null=True, verbose_name='Przyczyna przestoju 1'),
        ),
        migrations.AddField(
            model_name='interruption',
            name='cause_2',
            field=models.IntegerField(blank=True, choices=[(1, 'Cause')], null=True, verbose_name='Przyczyna przestoju 3'),
        ),
    ]
