# Generated by Django 2.0.5 on 2018-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0019_auto_20180913_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruption',
            name='cause_3',
            field=models.IntegerField(blank=True, choices=[(1, 'Cause')], null=True, verbose_name='Przyczyna przestoju 3'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='cause_2',
            field=models.IntegerField(blank=True, choices=[(1, 'Cause')], null=True, verbose_name='Przyczyna przestoju 2'),
        ),
    ]
