# Generated by Django 2.0.5 on 2018-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0020_auto_20180913_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='realization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy realizacja jest aktywna?'),
        ),
    ]
