# Generated by Django 2.0.5 on 2018-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0021_realization_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interruption',
            name='cause_1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Przyczyna przestoju 1'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='cause_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Przyczyna przestoju 2'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='cause_3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Przyczyna przestoju 3'),
        ),
        migrations.AlterField(
            model_name='interruption',
            name='realization',
            field=models.ForeignKey(null=True, on_delete=True, to='cms_app.Realization', verbose_name='Realizacja'),
        ),
    ]
