# Generated by Django 2.0.5 on 2018-09-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0023_realization_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realization',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='interruption',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Czy przestój jest zamknięty?'),
        ),
    ]
