# Generated by Django 2.0.5 on 2018-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0024_auto_20180914_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruption',
            name='was_alerted',
            field=models.BooleanField(default=False, verbose_name='Czy przestój jest zamknięty?'),
        ),
    ]
