# Generated by Django 2.0.5 on 2018-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0026_dbname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(verbose_name='Numer zlecenia'),
        ),
    ]
